import type { RouteRecordRaw } from 'vue-router'

export const triRoutes: RouteRecordRaw[] = [
  { path: 'tri/contacts', name: 'tri-contacts', component: () => import('@/pages/tri/contacts/ContactList.vue') },
  { path: 'tri/contacts/new', name: 'tri-contact-new', component: () => import('@/pages/tri/contacts/ContactForm.vue'), meta: { requiresWrite: true } },
  { path: 'tri/contacts/:id(\\d+)', name: 'tri-contact-detail', component: () => import('@/pages/tri/contacts/ContactDetail.vue') },
  { path: 'tri/contacts/:id(\\d+)/edit', name: 'tri-contact-edit', component: () => import('@/pages/tri/contacts/ContactForm.vue'), meta: { requiresWrite: true } },
  { path: 'tri/jobs', name: 'tri-jobs', component: () => import('@/pages/tri/jobs/JobList.vue') },
  { path: 'tri/jobs/new', name: 'tri-job-new', component: () => import('@/pages/tri/jobs/JobForm.vue'), meta: { requiresWrite: true } },
  { path: 'tri/jobs/:id(\\d+)', name: 'tri-job-detail', component: () => import('@/pages/tri/jobs/JobDetail.vue') },
  { path: 'tri/jobs/:id(\\d+)/edit', name: 'tri-job-edit', component: () => import('@/pages/tri/jobs/JobForm.vue'), meta: { requiresWrite: true } },
  { path: 'tri/jobs/:jobId(\\d+)/variants/:variantId(\\d+)', name: 'tri-variant-edit', component: () => import('@/pages/tri/jobs/VariantEditor.vue'), meta: { requiresWrite: true } },
  { path: 'tri/price-lists', name: 'tri-price-lists', component: () => import('@/pages/tri/price-lists/PriceListList.vue') },
  { path: 'tri/price-lists/new', name: 'tri-price-list-new', component: () => import('@/pages/tri/price-lists/PriceListEditor.vue'), meta: { requiresWrite: true } },
  { path: 'tri/price-lists/:id(\\d+)', name: 'tri-price-list-edit', component: () => import('@/pages/tri/price-lists/PriceListEditor.vue') },
  { path: 'tri/invoices', name: 'tri-invoices', component: () => import('@/pages/tri/invoices/InvoiceList.vue') },
  { path: 'tri/invoices/new', name: 'tri-invoice-new', component: () => import('@/pages/tri/invoices/InvoiceEditor.vue'), meta: { requiresWrite: true } },
  { path: 'tri/invoices/:id(\\d+)', name: 'tri-invoice-detail', component: () => import('@/pages/tri/invoices/InvoiceDetail.vue') },
  { path: 'tri/invoices/:id(\\d+)/edit', name: 'tri-invoice-edit', component: () => import('@/pages/tri/invoices/InvoiceEditor.vue'), meta: { requiresWrite: true } },
  { path: 'tri/travelers', name: 'tri-travelers', component: () => import('@/pages/tri/travelers/TravelerList.vue') },
  { path: 'tri/travelers/:id(\\d+)', name: 'tri-traveler-detail', component: () => import('@/pages/tri/travelers/TravelerDetail.vue') },
  { path: 'tri/calendar', name: 'tri-calendar', component: () => import('@/pages/tri/calendar/CalendarPage.vue') },
  { path: 'tri/complaints', name: 'tri-complaints', component: () => import('@/pages/tri/complaints/ComplaintList.vue') },
  { path: 'tri/complaints/:id(\\d+)', name: 'tri-complaint-detail', component: () => import('@/pages/tri/complaints/ComplaintDetail.vue') },
  { path: 'admin/tri-tags', name: 'tri-tags', component: () => import('@/pages/tri/admin/TagAdmin.vue'), meta: { adminOnly: true } },
]
